Vagrant.configure("2") do |config|
  config.vm.define "makS" do |makS|
    makS.vm.box = "debian/bookworm64"
    makS.vm.network "private_network", ip: "192.168.56.110"

    makS.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
    makS.vm.provision "shell", inline: <<-SHELL
      bash /vagrant/scripts/init.sh
      bash /vagrant/scripts/agent.sh
      bash /vagrant/scripts/kube-yamls.sh
    SHELL
  end
 end

