Vagrant.configure("2") do |config|
  config.vm.define "makbulutS" do |makbulutS|
    makbulutS.vm.box = "debian/bookworm64"
    makbulutS.vm.network "private_network", ip: "192.168.56.110"

    makbulutS.vm.provider "virtualbox" do |vb|
      vb.cpus = 4
      vb.memory = "8096"
    end
    makbulutS.vm.provision "shell", inline: <<-SHELL
      bash /vagrant/scripts/init.sh
      bash /vagrant/scripts/install_gitlab.sh
    SHELL
  end
 end

