Vagrant.configure("2") do |config|
  config.vm.define "makS" do |makS|
    makS.vm.box = "debian/bookworm64"
    makS.vm.network "private_network", ip: "192.168.56.110"

    makS.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "4096"
    end
    makS.vm.provision "shell", inline: <<-SHELL
      sh /vagrant/scripts/install_gitlab.sh
      sh /vagrant/scripts/init.sh
    SHELL
  end
 end

